// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------
// Modification history:
// feature: Modify test cases
// ------------------------------------------------------------------

/*!
 * @file HelloWorldPubSubMain.cpp
 * This file acts as a main entry point to the application.
 *
 * This file was generated by the tool vbscdrgen.
 */

#include "HelloWorldPublisher.h"
#include "HelloWorldSubscriber.h"

using vbsutil::elog::Log;

using namespace evbs::ertps;

int main(int argc, char** argv) {
    int type = 1;
    std::string xml_config_file = "perf9_udp.xml";
    std::cout << "Starting " << std::endl;

    for (int32_t i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-pub") == 0) {
            type = 1;
        } else if (strcmp(argv[i], "-sub") == 0) {
            type = 2;
        } else if (strcmp(argv[i], "-xml") == 0) {
            xml_config_file = std::string(argv[i + 1]);
            i++;
        }
    }

    switch (type) {
        case 1: {
            HelloWorldPublisher mypub;
            if (mypub.init(xml_config_file)) {
                std::cout << "Starting " << std::endl;
                mypub.run();
            }
            break;
        }
        case 2: {
            HelloWorldSubscriber mysub;
            if (mysub.init(xml_config_file)) {
                std::cout << "Starting " << std::endl;
                mysub.run();
            }
            break;
        }
    }

    return 0;
}
